export const introContent = {
  definitii: {
    title: '📚 Definiții',
    points: [
      'Neuropsihologia = subdisciplină a psihologiei',
      'Două domenii: clinic și experimental',
      'Neuropsihologie experimentală = Neuropsihologie cognitivă = Neuroștiințe cognitive',
      'Premisă: comportamentul observat = rezultat al activității din creier',
    ],
  },
  ipoteze: {
    title: '💭 Ipoteze Istorice',
    points: [
      'Ipoteza cardiocentrică: inima = sediul cogniției',
      '  • Empedocles',
      '  • Aristotel - creierul răcește sângele',
      'Ipoteza cefalocentrică: creierul = sediul cogniției',
      '  • Hipocrate',
      '  • Galen',
    ],
  },
  dualismul: {
    title: '⚖️ Problema Minte-Corp',
    points: [
      'René Descartes',
      '  • Dualismul: lume materială (corp) vs lume mentală (suflet)',
      '  • Glanda pineală = intermediar între creier și suflet',
      '  • Inspirație din mecanica și hidraulica',
      'Monismul: mintea și corpul = același lucru',
    ],
  },
  leziuni: {
    title: '🔬 Studii cu Leziuni',
    points: [
      'Jean-Cesar Legallois',
      '  • Prima localizare funcțională: nodul vital / centrul respirației',
      '  • Bulbul rahidian (medulla oblongata)',
      'Franz Joseph Gall',
      '  • Părintele frenologiei (teoria discreditată)',
      '  • Forma craniului → personalitate',
      'Marie-Jean-Pierre Flourens',
      '  • Critic al frenologiei',
      '  • Susținător al echipotențialității (fără specializare funcțională)',
      '  • Mitul 10% din creier folosit',
      'David Ferrier',
      '  • Dovedește echipotențialitatea greșită',
      '  • Localizare clară: funcție motrică și senzorială',
      'Friedrich Goltz',
      '  • Mărimea leziunii = cantitatea funcției pierdute',
      'Gustav Fritsch & Eduard Hitzig',
      '  • Cortexul frontal al câinelui',
      '  • Implicat în comanda motrică',
      'Paul Broca',
      '  • Pacient: Monsieur Tan',
      '  • Afazia lui Broca: afecțiune în producerea limbajului',
      '  • Localizată în lobul temporal',
      'Carl Wernicke',
      '  • Afazia lui Wernicke: inabilitatea înțelegerii limbajului',
    ],
  },
  anatomice: {
    title: '🔬 Studii Anatomice',
    points: [
      'Neajunsuri structurale rezolvate:',
      '  • Mărimea celulelor (0.02mm) → Microscopul',
      '  • Textura delicată → Întărire cu formaldehidă',
      '  • Lipsa pigmentării → Colorarea histologică (Nissl, Golgi, Cajal)',
    ],
  },
  electrice: {
    title: '⚡ Proprietăți Electrice & Chimice',
    points: [
      'Benjamin Franklin - electricitatea',
      'Luigi Galvani & Emil du Bois-Reymond',
      '  • Galvanometrul: măsurare potențial electric în mușchi',
      'Charles Sherrington',
      '  • Reflexele',
      '  • A denumit sinapsa',
      'Julius Bernstein',
      '  • Viteza de conducere pe axon',
      '  • A introdus potențialul de acțiune',
      'Alan Hodgkin & Andrew Huxley',
      '  • Potențialul de acțiune și permeabilitatea membranei',
      'Otto Loewi',
      '  • Descoperă neurotransmițătorul vagusstoff (acetilcolină)',
      '  • Lucru pe inima de broască',
      'Henry Dale & Julius Axelrod',
      '  • Continuă munca lui Loewi',
    ],
  },
  cartografiere: {
    title: '🗺️ Cartografierea Creierului',
    points: [
      'Korbinian Broadmann',
      '  • Citoarhitectonică: împarte creierul în zone funcționale',
      '  • Pe baza tipului de celulă nervoasă predominantă',
      '  • Zonele Broadmann - folosite și astăzi (RMN)',
      'Wilder Penfield',
      '  • Homunculus: localizarea cortexului somatosenzorial',
      '  • Neurochirurgie funcțională + stimulare electrică',
      '  • Pe pacienți cu epilepsie treji',
    ],
  },
};

export const neuronSections = {
  structura: {
    title: '🧍 STRUCTURA NEURONULUI-OM',
    content: [
      {
        subtitle: '⚡ Neuron (Neuronul) = OMUL COMPLET',
        points: [
          '— Basic nerve cell (celula nervoasă de bază)',
          '— Specialized for information transmission (transmiterea informației)',
          '— Unique structure: are axon (axon) - întâlnit DOAR la neurons (neuroni)',
        ],
      },
      {
        subtitle: '🧠 Cell Body / Soma (Corpul Celular) = CAPUL',
        points: [
          '— Command center (centrul de comandă) al neuronului-om',
          '— Conține nucleus (nucleul) - creierul intern',
          '— Produce energia necesară funcționării',
        ],
      },
      {
        subtitle: '🦴 Axon (Axonul) = CORPUL',
        points: [
          '— Corpul principal prin care călătorește informația',
          '— Highly specialized (foarte specializat) pentru information transmission (transmiterea informației)',
          '— Collateral branches (ramurile colaterale) = picioarele',
          '— Se termină în câteva terminații',
          '— Terminal buttons (butoni terminali) = degetele de la picioare care ating alți neuroni',
          '— Formează synapse (sinapsă) cu alți neurons (neuroni)',
        ],
      },
      {
        subtitle: '💇 Dendrites (Dendritele) = PĂRUL DE PE CAP',
        points: [
          '— Fire ramificate care primesc mesaje',
          '— Primesc informația în synaptic transmission (transmisia sinaptică)',
          '— Acoperite de receptors (receptori) = radăcini senzoriale',
          '— Receptors = molecules (molecule) care detect (detectează) și attract (atrag) neurotransmitters (neurotransmițătorii)',
          '— Cu cât mai multe dendrites (dendrite), cu atât mai multe "antene"',
        ],
      },
      {
        subtitle: '🧥 Myelin Sheath (Teaca de Mielină) = PIELEA PROTECTOARE',
        points: [
          '— Înveliș izolant în jurul axon-ului (axonului-corp)',
          '— Nodes of Ranvier (noduri Ranvier) = articulații descoperite',
          '— Myelin (mielina) increases speed (mărește viteza) cu care signals (semnalele) călătoresc de-a lungul axon-ului (axonului)',
          '— Accelerează transmisia electrical signal-ului (semnalului electric)',
        ],
      },
      {
        subtitle: '🔗 Synaptic Cleft (Fanta Sinaptică) = SPAȚIUL DINTRE DEGETE',
        points: [
          '— Synaptic transmission (transmisia sinaptică) se realizează aici',
          '— Release (eliberare) de neurotransmitters (neurotransmițători)',
          '— Communication space (spațiul de comunicare) între neurons (neuroni)',
        ],
      },
    ],
  },
  glia: {
    title: '👥 ECHIPA DE SUPORT - GLIA',
    content: [
      {
        subtitle: '🌟 Glial Cells (Celulele Gliale) = ECHIPA DE SUPORT',
        points: [
          '— Parte a nervous system (sistemului nervos)',
          '— Nu sunt neurons (neuroni), dar sunt esențiale',
          '— Mai multe tipuri cu roluri diferite',
        ],
      },
      {
        subtitle: '⭐ Astrocytes (Astrocitele) = PERSONALUL MEDICAL',
        points: [
          '— Star-shaped form (forma stelată) = asistente în jurul neurons (neuronilor)',
          '— Găsite în jurul synapses (sinapselor) și nodes of Ranvier (nodurilor Ranvier)',
          '— Contribute (contribuie) la blood-brain barrier (bariera creier-sânge)',
          '— Classic roles (roluri clasice):',
          '  • Absorption and inactivation (absorbția și inactivarea) neurotransmitters (neurotransmițătorilor)',
          '  • Detoxification/cleaning (detoxifierea/curățarea) nervous system (sistemului nervos)',
          '— Mențin blood-brain barrier (bariera creier-sânge) = sistemul de securitate',
        ],
      },
      {
        subtitle: '🧬 Myelinating Glia (Glia Mielinizantă) = CROITORII',
        points: [
          '— Formată din două tipuri de cells (celule)',
          '— Role (rol): izolează axons (axonii) prin crearea myelin sheath (tecii de mielină)',
        ],
      },
      {
        subtitle:
          '🔬 Oligodendrocytes (Oligodendrocite) în CNS / SNC = CROITORII INTERNI',
        points: [
          '— Oligodendroglial cells (celule oligodendrogliale) în Central Nervous System (sistemul nervos central)',
          '— Creează myelin sheath (teaca de mielină) în brain (creier)',
          '— Înfășoară axons (axonii) pentru insulation (izolație)',
          '— Un oligodendrocyte (oligodendrocit) = mai mulți neurons (neuroni) îmbrăcați',
          '— Poate mieliniza multiple axons (axoni multipli) simultan',
        ],
      },
      {
        subtitle:
          '🦠 Schwann Cells (Celule Schwann) în PNS / SNP = CROITORII EXTERNI',
        points: [
          '— Acționează în Peripheral Nervous System (sistemul nervos periferic)',
          '— Myelinate (mielinizează) axons (axonii) din peripheral nerves (nervii periferici)',
          '— O Schwann cell (celulă Schwann) = un singur axon segment (segment de axon)',
          '— Permit regeneration (regenerarea) peripheral nerves (nervilor periferici)',
          '— Relație 1:1 cu axon segments (segmentele de axon)',
        ],
      },
    ],
  },
  comunicare: {
    title: '⚡ COMUNICAREA ELECTRICĂ',
    content: [
      {
        subtitle:
          'Resting Potential (Potențial de Repaus) = STAREA DE AȘTEPTARE',
        points: [
          'Neuronul-om stă liniștit la resting membrane potential (potențial de membrană de repaus) de -65mV',
          'Na+ (sodiu) vrea să intre (ca fanii înainte de concert)',
          'K+ (potasiu) "picură" afară (ca niște spectatori plictisiți)',
          'Cell membrane (membrana) = ușa cu selective ion channels (portari selectivi / canale ionice selective)',
        ],
      },
      {
        subtitle: 'Action Potential (Potențial de Acțiune) = UNDA DE ENERGIE',
        points: [
          'Stimulus (stimul) ajunge → Se deschid Na+ gates (porțile Na+)',
          'DEPOLARIZATION (DEPOLARIZARE): Na+ intră în avalanșă → membrane (membrana) devine pozitivă',
          'OVERSHOOT: Moment scurt de positivitate (+40mV)',
          'REPOLARIZATION (REPOLARIZARE): K+ iese → revenire la negativ',
          'UNDERSHOOT (HIPERPOLARIZARE): Depășire temporară sub -65mV',
        ],
      },
      {
        subtitle:
          'All-or-None Principle (Principiul "Tot sau Nimic") = ARTIFICIUL',
        points: [
          'Odată aprins, arde până la capăt',
          'Nu există action potential (potențial de acțiune) "slab" sau "puternic"',
          'Duration (durată): ~2 milliseconds (milisecunde)',
          'Speed (viteză): ~10 m/s (mai rapid cu myelin / mielină)',
        ],
      },
      {
        subtitle: 'Information Coding (Codificarea Informației)',
        points: [
          'INTENSITY (INTENSITATE) = frequency (frecvența) potențialelor (max ~1000Hz)',
          'Strong stimulus (stimul puternic) = mai multe action potentials (potențiale)/secundă',
          'Distribution (distribuția) active neurons (neuronilor activi) = message pattern (pattern-ul mesajului)',
        ],
      },
    ],
  },
};

export const anatomieContent = {
  referinte: {
    title: '🧭 Referințe Poziționale de Bază',
    points: [
      'Neuroaxa = axă imaginară de-a lungul sistemului nervos',
      '  • De la partea cea mai de jos a măduvei spinării',
      '  • Până la partea cea mai de sus a creierului',
      '  • Permite delimitarea referințelor poziționale',
      'Planuri de feliere:',
      '  • Orizontale (axiale, transversale)',
      '  • Frontale (coronale)',
      '  • Sagitale (longitudinale)',
      'Terminologie:',
      '  • Ipsilaterale = structuri în aceeași emisferă',
      '  • Contralaterale = structuri în emisfere diferite',
    ],
  },
  diviziuni: {
    title: '🌳 Diviziuni ale Sistemului Nervos',
    points: [
      'Sistemul Nervos Central (SNC):',
      '  • Creierul',
      '  • Măduva spinării',
      '  • Protejate de os',
      'Sistemul Nervos Periferic (SNP):',
      '  • Sistem nervos somatic:',
      '    - Control voluntar al nervilor spinali',
      '    - Inervează pielea, articulațiile, mușchii',
      '    - Nervi eferenți (merg către periferie, ventral)',
      '    - Nervi aferenți (informație senzorială către creier, dorsal)',
      '  • Sistem nervos autonom (visceral):',
      '    - Control automatic: organe, vase sanguine, glande',
      '    - Sistem nervos simpatic',
      '    - Sistem nervos parasimpatic',
    ],
  },
  anterior: {
    title: '🧠 Creierul Anterior (Prozencefalul)',
    points: [
      'Sediul conștiinței, senzației și percepției',
      'Format din: Telencefal și Diencefal',
      '',
      'TELENCEFALUL - Cele două emisfere cerebrale:',
      '',
      'Cortexul:',
      '  • Materia cenușie = corpurile celulelor nervoase',
      '  • Organizată ca "pătură ridată" în gyri (ridicături) și sulci (șanțuri/fisuri)',
      '  • Substanța albă = axonii celulelor nervoase:',
      '    - Substanța albă corticală (axoni de la/către neuroni în cortex)',
      '    - Corpul calos (unește cele două emisfere)',
      '    - Capsula internă (unește cortexul cu trunchiul cerebral)',
      '',
      'Cei 4 Lobi:',
      '  • Frontal: planificare, control motric, memorie, inhibiție, comportament social',
      '  • Parietal: senzorimotor, percepția spațiului, atenție',
      '  • Temporal: procesare limbaj, memorie, recunoaștere obiecte, emoție',
      '  • Occipital: procesare informație vizuală',
      '  • Fisuri importante: longitudinală, laterală (Sylviană), centrală',
      '',
      'Ganglionii Bazali:',
      '  • Inițierea mișcării și menținerea tonusului muscular',
      '  • Nucleul caudat + Putamen = Striatum (structură striată)',
      '  • Putamen + Globul palid = Nucleul lentiform',
      '',
      'Sistemul Limbic:',
      '  • Încercuiește ganglionii bazali și thalamus',
      '  • Amygdala: emoție, învățare afectivă',
      '  • Hippocampus: memorie',
      '  • Fornix',
      '  • Corpuri mamilare: memorie',
      '  • Cortex limbic',
      '',
      'DIENCEFALUL - "Creierul dinăuntru":',
      '',
      'Thalamus:',
      '  • Structură ovoidală',
      '  • Poartă internă/releu pentru informație senzorială și motricitate',
      '  • Legătură prin capsula internă către cortex',
      '',
      'Hypothalamus:',
      '  • Cluster de nuclei pentru control autonom și endocrin',
      '  • Glanda hipofiză: eliberare hormoni',
      '  • Funcții primitive: "fight or flight"',
    ],
  },
  mijlociu: {
    title: '🔗 Creierul Mijlociu (Mezencefalul)',
    points: [
      'Funcție: conexiune între măduva spinării și creierul anterior',
      'Important pentru: senzație și control motric',
      '',
      'TECTUM (deasupra, acoperiș):',
      '  • Coliculul superior: esențial pentru văz',
      '  • Coliculul inferior: auz',
      '',
      'TEGMENTUM (dedesubt, podea):',
      '  • Nucleul roșu: control motric',
      '  • Substanța neagră: control motric',
    ],
  },
  posterior: {
    title: '🎯 Creierul Posterior (Rombencefalul)',
    points: [
      'Cerebellum (creierul mic):',
      '  • Control motric, timing',
      '',
      'Puntea:',
      '  • Transmite informație de la cortexul cerebral la cerebel',
      '',
      'Bulbul rahidian (medulla oblongata):',
      '  • Funcții de bază, vegetative',
      '  • Susține viața',
    ],
  },
  comisuri: {
    title: '🔄 Conexiuni între Emisfere',
    points: [
      'Comisurile (vizibile în tăieturi sagitale):',
      '  • Comisura anterioară',
      '  • Comisura posterioară',
      '  • Corpul calos',
    ],
  },
  cranieni: {
    title: '🧵 Nervi Cranieni',
    points: [
      '12 nervi cranieni specializați pentru funcții specifice',
      'Se studiază împreună cu funcțiile respective',
    ],
  },
  vascular: {
    title: '🩸 Teritoriu Vascular',
    points: [
      'Artere care intră în creier (vizibile ventral):',
      '  • 2 artere vertebrale (posterior)',
      '  • 2 artere carotide interne (anterior)',
      '  • Se întâlnesc în artera basilară',
      '',
      'Artere principale:',
      '  • Arterele cerebrale anterioare',
      '  • Arterele cerebrale din mijloc',
      '  • Arterele cerebrale posterioare',
    ],
  },
  protectie: {
    title: '🛡️ Protecția Sistemului Nervos',
    points: [
      '1. OS',
      '',
      '2. MENINGELE (3 membrane):',
      '  • Dura mater: "mamă dură", înveliș exterior',
      '  • Arachnoid mater: membrană arahnoidă (pânză de păianjen)',
      '    - Include spațiul sub-arachnoid',
      '  • Pia mater: "mamă blândă", membrană subțire',
      '    - Lipită de suprafața creierului',
      '    - Separată de arachnoid prin spațiu cu lichid cefalorahidian',
      '',
      '3. SISTEM VENTRICULAR:',
      '  • Lichid cefalorahidian',
      '  • 2 ventricole laterale',
      '  • Ventricolul 3 & 4',
      '  • Apeductul cerebral',
      '',
      '4. BARIERA SÂNGE-CREIER:',
      '  • Demonstrată de Edwin Goldmann & Paul Ehrlich',
      '  • Separare între lichidul cefalorahidian și vasculatura corpului',
    ],
  },
};

export const metode1Content = {
  principii: {
    title: '🔬 Principii Metodă Științifică',
    points: [
      'Obiectivitate',
      'Metodă empirică',
      'Replicabilitate',
      'Condiții de control',
      'Considerarea variabilelor parazite',
      '',
      'Predicție/Ipoteză oglindită în literatură',
      'Variabile independente = manipulate',
      'Variabile dependente = măsurate',
      '',
      'Cea mai bună abordare = metodologie multidisciplinară',
    ],
  },
  tumori: {
    title: '🧠 Tumori Cerebrale',
    points: [
      'Definiție: grupare de țesut nou (neoplasm) și anormal',
      'Clasificare după:',
      '  • Tipul de celulă',
      '  • Timpul de creștere',
      '  • Tipul de creștere: încapsulate vs infiltrate',
      '  • Recidivă: benigne (nu recidivează) vs maligne (recidivează)',
      '',
      '4 TIPURI:',
      '',
      '1. Tumori din celule gliale (gliom) - cele mai comune:',
      '  • Astrocitom: creștere moderată, încapsulat, rar malign',
      '  • Glioblastom: foarte malign, creștere rapidă, se infiltrează',
      '  • Medulloblastom: crește în bulbul rahidian (centri vitali), prognoză scăzută',
      '',
      '2. Tumori din meninge (meningiom):',
      '  • Cresc încapsulate',
      '  • Atașate de meninge, în afara SNC',
      '  • De obicei benigne',
      '  • Problemă: presiune intra-craniană',
      '',
      '3. Tumori din țesut nervos',
      '',
      '4. Tumori metastatice (secundare):',
      '  • Se formează din țesut tumoral care migrează',
      '  • De obicei din afara SNC (plămân, uter)',
      '  • Pot fi simple sau multiple',
      '',
      'Important: Toate tipurile → efect comportamental',
    ],
  },
  cerebrovasculare: {
    title: '🩸 Tulburări Cerebrovasculare',
    points: [
      'Cea mai importantă cauză de deteriorare neurologică',
      'Definiție: întreruperea aportului de sânge la creier',
      '',
      'AVC (Accident Vascular Cerebral) - VIP:',
      '  • Întrerupere bruscă sau graduală (ani)',
      '  • Rezultă în ischemie cerebrală (lipsa aportului de sânge)',
      '  • Infarct: ischemie severă și de lungă durată',
    ],
  },
  raniri: {
    title: '🤕 Rănirea Capului (Traumatic Brain Injury)',
    points: [
      'Afectează mai mult:',
      '  • Populația tânără',
      '  • Bărbați > femei',
      '  • La adulți: consecințe mai severe',
      '',
      'Consecințe: tulburări cognitive',
      '',
      'Tipuri:',
      '  • Rană deschisă (mai puțin periculoasă)',
      '  • Rană închisă (mai periculoasă!) - implică pierderea conștiinței',
      '',
      'Coup vs Contre-coup:',
      '  • Creierul plutește în lichid cefalorahidian',
      '  • Lovitură puternică → împingere în peretele opus',
      '',
      'Pacient celebru: Phineas Gage (rană severă deschisă)',
    ],
  },
  infectii: {
    title: '🦠 Infecții & Neurotoxine',
    points: [
      'Infecții cerebrale:',
      '  • Cauze: bacterii, viruși, paraziți (din afara SNC)',
      '  • Meningita bacteriană: șanse de vindecare cu antibiotice',
      '  • Meningita virală: mult mai greu de tratat',
      '  • Simptome: febră crescută, durere de cap intensă, gât rigid',
      '',
      'Neurotoxine:',
      '  • Găsite în: solvenți, pesticide, metale grele, combustibili',
      '  • Dozajul contează (expunere)',
      '  • Exemplu: Pălărierul nebun (Mad Hatter) - mercur la confecționarea pălăriilor',
    ],
  },
  tms: {
    title: '⚡ TMS - Leziuni Virtuale',
    points: [
      'TMS (Stimulare Magnetică Transcraniană):',
      '  • Leziuni virtuale de durată foarte scurtă',
      '  • Metodă neinvazivă',
      '  • Câmpuri electromagnetice prin bobină în formă de opt',
      '  • Modulează activitatea electrică din creier',
      '',
      'Tipuri de stimulare:',
      '  • Unică: un puls per trial',
      '  • Repetată: grup de pulsuri de-a lungul trial-urilor',
      '',
      'Limită motrică (pentru fiecare participant):',
      '  • Intensitatea minimă care produce potențial motric evocat',
      '  • Căutare cortex motric (anterior sulcusului central)',
      '  • Aplicare pe cortexul pentru degetul arătător (homunculus motor)',
      '  • Intensitatea diferă de la participant la participant',
      '',
      'Condiții de control:',
      '  • Fără TMS',
      '  • Sham TMS: bobină pe altă regiune sau întoarsă invers (zgomot fără stimulare)',
      '',
      'Folosit împreună cu: metode comportamentale și/sau imagistică cerebrală',
      '',
      'Efecte observabile:',
      '  • Peste cortex motric: tresărirea mușchilor',
      '  • Peste cortex vizual: fosfene',
      '  • Peste centrii vorbirii (lob temporal): vorbire neclară',
    ],
  },
  tdcs: {
    title: '🔋 tDCS - Îmbunătățirea Funcției Psihice',
    points: [
      'tDCS (Stimulare Transcraniană prin Curent Continuu):',
      '  • Dezvoltată din TMS, cu alte specificații',
      '',
      'Caracteristici:',
      '  • Doi electrozi:',
      '    - Anod: hiperpolarizare',
      '    - Catod: depolarizare',
      '  • Amplitudine scăzută, constantă: 1-2mA',
      '  • Durată mai lungă: 5-30 minute',
      '',
      'Parametri variabili:',
      '  • Mărimea, forma, aranjarea electrozilor',
      '  • Polaritatea, amplitudinea, durata curentului',
      '',
      'Aplicații:',
      '  • Ameliorarea depresiei (stimulare repetată)',
      '  • Îmbunătățirea funcțiilor cognitive',
    ],
  },
};

export const metode2Content = {
  eeg_intro: {
    title: '📊 Electroencefalografie (EEG)',
    points: [
      'Nașterea EEG: începutul secolului XX',
      'Hans Berger: primele experimente',
      '  • Măsurat activitatea neuronală',
      '  • Un singur electrod pe scalp',
      '',
      'Definiție: metodă care înregistrează semnale electrice din creier prin electrozi pe scalp',
      '',
      'Baza: principii de potențial de membrană și potențial de acțiune aplicate la grupuri de neuroni',
    ],
  },
  eeg_setup: {
    title: '🎧 Sistemul EEG',
    points: [
      'Cască cu electrozi:',
      '  • Așezați conform sistemul 10-20 (standard științific)',
      '  • Referințe fiziologice: inion, nasion, cei doi mastoizi',
      '  • Aceeași locație pentru toți participanții (diferite circumferințe cap)',
      '',
      'Denumirea electrozilor:',
      '  • După cei 4 lobi cerebrali',
      '  • Numere impare = emisfera stângă',
      '  • Numere pare = emisfera dreaptă',
      '',
      'Tipuri electrozi:',
      '  • Electrozi pasivi (Ag/AgCl): timp atașare câteva ore',
      '  • Electrozi activi: circuite integrate, impedanță minimă, câteva minute',
      '',
      'Procesare semnal:',
      '  • Trece prin amplificator',
      '  • Vizualizat pe computer (linie ca o "mâzgălitură")',
    ],
  },
  eeg_artefacte: {
    title: '⚠️ Artefacte EEG',
    points: [
      'Participantul NU trebuie să:',
      '  • Miște capul/corpul',
      '  • Miște ochii',
      '  • Clipească',
      '  • Mestece',
      '',
      'Consecință mișcare: deteriorare accentuată a semnalului → date nefolosite',
    ],
  },
  eeg_aplicatii: {
    title: '🏥 Aplicații Clinice EEG',
    points: [
      'Diagnostic:',
      '  • Epilepsie',
      '  • Coma',
      '  • Moarte cerebrală',
      '',
      'Distingere stări mentale:',
      '  • Om sănătos vs patologie',
      '  • Activitate intelectuală',
      '  • Stări diverse: somnoros, relaxat',
      '',
      'Diverse frecvențe măsurate în funcție de sarcina cognitivă',
    ],
  },
  erp: {
    title: '⚡ Potențiale Evocate (ERPs)',
    points: [
      'Event-Related Potentials (ERPs):',
      '  • Potențiale în răspuns la un eveniment de interes',
      '  • Prezentare eveniment pe mai multe trials',
      '  • Aliniere la timpul 0 al stimulării',
      '',
      'Caracterizare:',
      '  • Polaritate: negativ vs pozitiv',
      '  • Timp de apariție: milisecunde de la timpul 0',
      '',
      '2 CATEGORII:',
      '',
      '1. Potențiale EXOGENE (devreme):',
      '  • Reflectă caracteristici perceptuale ale stimulului',
      '  • N1 vizual',
      '  • N140: procesare stimuli tactili',
      '  • N170: legat de fețele umane',
      '',
      '2. Potențiale ENDOGENE (târziu):',
      '  • Legate de funcții înalte',
      '  • LPP (Late Positive Potential): procesare informație afectivă',
    ],
  },
  eeg_avantaj: {
    title: '✅ Avantaje EEG',
    points: [
      'Dezavantaj: Nu cunoaștem sursa spațială exactă',
      '',
      'AVANTAJ MAJOR: Rezoluție temporală excelentă',
      '  • Ne-invaziv',
      '  • Monitorizare până la 1-câteva milisecunde',
      '  • Depinde de rata de eșantionare',
    ],
  },
  rmn_intro: {
    title: '🧲 Rezonanța Magnetică Nucleară (RMN)',
    points: [
      '2 TIPURI:',
      '',
      '1. Imagistică STRUCTURALĂ:',
      '  • Pentru diagnostic',
      '  • Hărți statice ale creierului',
      '  • Rezoluție foarte înaltă',
      '',
      '2. Imagistică FUNCȚIONALĂ (fMRI):',
      '  • Cadru experimental',
      '  • Hărți dinamice ale creierului',
      '  • Rezoluție moderată',
      '',
      'Baza: Diverse tipuri de țesut (craniu, materie cenușie, materie albă, lichid cefalorahidian) au proprietăți fizice diferite',
    ],
  },
  scanner: {
    title: '🔬 Scanner-ul RMN',
    points: [
      'Puterea scanner-ului: dată de câmpul magnetic',
      '  • 1.5T sau 3T: diagnostic/cercetare umană standard',
      '  • 7T: imagistică de mare precizie (recent)',
      '',
      'Câmp magnetic extrem de puternic - Reguli de precauție:',
      '  • ❌ Obiecte metalice',
      '  • ❌ Implanturi (stimulatoare cardiace)',
      '  • ⚠️ Cerneala din tatuaje se supra-încălzește',
      '  • ⚠️ Substanțe din machiaj se supra-încălzește',
      '',
      'Necesar: aviz de la medic specializat pentru participare',
    ],
  },
  masurare: {
    title: '⚙️ Cum Măsurăm RMN',
    points: [
      '1. PROTON:',
      '  • Apa (H2O) = din abundență în corpul uman',
      '  • Protonii = nucleii de hidrogen din apă',
      '  • Au câmpuri magnetice foarte slabe',
      '  • Similar unui magnet: momentum angular și magnetic',
      '',
      '2. PRECESIE:',
      '  • Mișcare giroscopică (ca un titirez)',
      '  • Axa de rotire se rotește în jurul unei axe centrale',
      '  • Protonii în corp (orientați dezordonat) se aliniază paralel/anti-paralel câmpului magnetic static',
      '',
      '3. GRADIENTE MAGNETICE:',
      '  • Unde radio / pulsuri de excitare la 90°',
      '  • Schimbă alinierea protonilor la 90°',
      '  • Permite măsurarea semnalului de rezonanță magnetică',
      '',
      'PROCES:',
      '  • Magnetizare longitudinală: participant în câmpul magnetic',
      '  • Undă radio → magnetizare longitudinală = 0',
      '  • Timp T1 (secunde): revenire la valoarea maximă inițială',
      '  • Nouă undă radio pentru scanarea unei noi "felii"',
    ],
  },
  ce_masuram: {
    title: '📈 Ce Măsurăm în RMN',
    points: [
      'Timp T1 (relaxare):',
      '  • Distinge între tipuri de țesut',
      '  • Imagini T1: materie cenușie și materie albă',
      '  • Rezoluție înaltă',
      '  • Folosite în imagistică structurală (diagnostic)',
      '',
      'Magnetizare transversală:',
      '  • Decăderea semnalului datorită interacțiunii moleculare',
      '  • Timp T2 (milisecunde): necesar pentru revenire la 0',
      '  • Baza imaginilor T2* în RMN funcțional',
      '',
      'SEMNALUL BOLD (Blood-Oxygen-Level-Dependent):',
      '  • Oxihemoglobină: diamagnetică (repulsie)',
      '  • Deoxihemoglobină: paramagnetică (atracție)',
      '  • Ne interesează cantitatea de deoxihemoglobină',
      '  • Neuronii consumă oxigen → transformă oxihemoglobină în deoxihemoglobină',
      '  • Mai multă deoxihemoglobină = timp T2 mai scurt',
      '',
      'BOLD-contrast: diferența în semnal pe imaginile T2* = răspunsul hemodinamic (HDR)',
    ],
  },
  zgomot: {
    title: '⚠️ Distorsiuni & Pre-procesare',
    points: [
      'Surse de zgomot:',
      '  • Poluare termală',
      '  • Poluare sistem (scanner drift)',
      '  • Mișcare cap',
      '  • Zgomot fiziologic',
      '  • Variabilitate comportamentală/cognitivă',
      '',
      'Soluții:',
      '  • Design experimental potrivit',
      '  • Creșterea puterii câmpului magnetic',
      '  • Măsurători repetate',
      '',
      'PRE-PROCESARE:',
      '  • Inspecție vizuală',
      '  • Corectare timp achiziție "felii" (întretăiată vs ordine)',
      '  • Corectare mișcare cap',
      '  • Corectare distorsiuni',
      '  • Co-înregistrare imagini structurale și funcționale',
      '  • Normalizare în spațiu: Talairach sau MNI (Montreal Neurological Institute)',
      '  • Filtru temporal',
      '  • Filtru spațial (imagini încețoșate)',
    ],
  },
  rezolutie: {
    title: '🎯 Rezoluție RMN',
    points: [
      'AVANTAJ PRINCIPAL: Rezoluție spațială excelentă',
      '  • Identificare regiuni milimetrice din creier',
      '  • Dată de mărimea voxel-ului:',
      '    - Field of view (feliere la achiziție)',
      '    - Dimensiunea matricei',
      '    - Grosimea "feliei" înregistrate',
      '',
      'Rezoluție temporală: nu e strălucită',
      '  • Dată de "time to repeat" (timpul de repetare)',
      '  • Cât timp pentru a înregistra o nouă "felie"',
      '  • De obicei: câteva sute de milisecunde',
    ],
  },
};
